import { ITableSales } from "@/interfaces/Sales";

export const listTables: ITableSales[] = [
  {
    id: 1,
    textInformation: "Información 1",
    zone: 1,
    capacity: 4,
    people: 0,
    enabled: true,
  },
  {
    id: 2,
    textInformation: "Información 2",
    zone: 1,
    capacity: 4,
    people: 0,
    enabled: true,
  },
  {
    id: 3,
    textInformation: "Información 3",
    zone: 1,
    capacity: 4,
    people: 0,
    enabled: true,
  },
  {
    id: 4,
    textInformation: "Información 4",
    zone: 1,
    capacity: 4,
    people: 2,
    enabled: false,
  },
  {
    id: 5,
    textInformation: "Información 5",
    zone: 1,
    capacity: 4,
    people: 2,
    enabled: false,
  },
  {
    id: 11,
    textInformation: "Información 1",
    zone: 2,
    capacity: 4,
    people: 0,
    enabled: true,
  },
  {
    id: 12,
    textInformation: "Información 2",
    zone: 2,
    capacity: 4,
    people: 0,
    enabled: true,
  },
  {
    id: 13,
    textInformation: "Información 3",
    zone: 2,
    capacity: 4,
    people: 0,
    enabled: true,
  },
  {
    id: 14,
    textInformation: "Información 4",
    zone: 2,
    capacity: 4,
    people: 2,
    enabled: false,
  },
  {
    id: 15,
    textInformation: "Información 5",
    zone: 2,
    capacity: 4,
    people: 2,
    enabled: false,
  },
  {
    id: 21,
    textInformation: "Información 1",
    zone: 3,
    capacity: 4,
    people: 0,
    enabled: true,
  },
  {
    id: 22,
    textInformation: "Información 2",
    zone: 3,
    capacity: 4,
    people: 0,
    enabled: true,
  },
  {
    id: 23,
    textInformation: "Información 3",
    zone: 3,
    capacity: 4,
    people: 0,
    enabled: true,
  },
  {
    id: 24,
    textInformation: "Información 4",
    zone: 3,
    capacity: 4,
    people: 2,
    enabled: false,
  },
  {
    id: 25,
    textInformation: "Información 5",
    zone: 3,
    capacity: 4,
    people: 2,
    enabled: false,
  },
]